name: Test download artifact

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Branch
      uses: actions/checkout@v2
      with:
        path: current
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f current/requirements.txt ]; then pip install -r current/requirements.txt; fi
    - name: Run the Diff Checker
      run: |
        python current/artifact.py
    - name: upload_artifact
      uses: actions/upload-artifact@v2
      with:
         name: sarif
         path: /home/runner/work/codeql_test2/codeql_test2/dict.json
    - name: download_artifact
      uses: actions/download-artifact@v2
      with:
        name: sarif
        path: /home/runner/work/codeql_test2/

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /home/runner/work/codeql_test2/
    - name: Push To Datadog
      run: |
        python current/push.py
